In [6]:
import numpy as np

a = np.array([2,4,6])
print(a)

[2 4 6]


In [4]:
a = np.array([(1, 2), (3, 4), (5,6)])
a.shape

(3, 2)

In [5]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a[0,2])

2


In [7]:
import numpy as np

a = np.array([2,4,6])
print(a)
value = a[2]
print(value)

[2 4 6]
6


In [8]:
import numpy as np

a = np.array([2, 4, 6, 8])
print(a)
b = a[1:]
print(b)

[2 4 6 8]
[4 6 8]


In [9]:
import numpy as np
value=np.random.random()
print(value)

0.39628218478419486


In [10]:
import numpy as np
array=np.random.random((2,2))
print(array)

[[3.67289722e-02 2.81005164e-06]
 [5.64557010e-01 7.40702343e-01]]


NumPy Randint

In [12]:
import numpy as np
array=np.random.randint(2, 10, size=(2,4))
print(array)

[[3 9 8 3]
 [4 3 2 9]]


In [13]:
array=np.zeros(3)
print(array)

[0. 0. 0.]


In [14]:
array=np.full(3, 5)
print(array)

[5 5 5]


In [15]:
array=np.eye(2)
print(array)

[[1. 0.]
 [0. 1.]]


In [32]:
array=np.ones(shape =(2,4))
print(array)
array.ndim

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2

In [27]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)
Z=np.subtract(x, y)
print(Z)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[-4. -4.]
 [-4. -4.]]


In [43]:
import numpy as np

array1 = np.array(
    [[1, 2],
     [3, 4],
     [5, 6]])

total = np.sum(array1)
print(f'Sum of all the elements is {total}')

Sum of all the elements is 21


### Ask the user to enter the marks of each student in each subject.


In [55]:
n=int(input("enter number of students : "))
sub=int(input("enter number of subjects : "))
marks = np.zeros((n,sub))
for i in range(n):
    print(f"\nEntering marks for student {i + 1}:")
    for j in range(sub):
        marks[i, j] = float(input(f"Enter the marks for subject {j + 1}: "))
        

enter number of students :  2
enter number of subjects :  2



Entering marks for student 1:


Enter the marks for subject 1:  12
Enter the marks for subject 2:  13



Entering marks for student 2:


Enter the marks for subject 1:  24
Enter the marks for subject 2:  35


In [143]:
print(marks)

[[12. 13.]
 [24. 35.]]


In [82]:
for i in range(n):
   print(marks[i])

[12. 13.]
[24. 35.]


##### Calculate the total marks for each student using the sum() function of Numpy

In [118]:
total_1=[]
for i in range(n):
    total= np.sum(marks[i]) 
    print(total)
    total_1.append(total)
print (total_1)

25.0
59.0
[25.0, 59.0]


###### Calculate the percentage for each student using the total marks and the formula: percentage = (total marks / (number of subjects * 100)) * 100

In [120]:
percentage_1=[]
for i in range(n):
       percentage= (total_1[i] / (sub * 100)) * 100
       print(percentage,"%")
       percentage_1.append(percentage)
print(percentage_1)



12.5 %
29.5 %
[12.5, 29.5]


## Calculate the grade for each student using the percentage and the following grading system:
90% or above: A+
80% or above: A
70% or above: B+
60% or above: B
50% or above: C
below 50%: F

In [140]:
grades=[]
for i in range(n):
    if percentage_1[i] >= 90:
        print(f"the grade for student {i+1} is A+")
        grades.append("A+")
    elif percentage_1[i] >= 80:
        print(f"the grade for student {i+1} is A")
        grades.append("A")
    elif percentage_1[i] >= 70:
        print(f"the grade for student {i+1} is B+")
        grades.append("B+")
    elif percentage_1[i] >= 60:
        print(f"the grade for student {i+1} is B")
        grades.append("B")
    elif percentage_1[i] >= 50:
        print(f"the grade for student {i+1} is C")
        grades.append("C")
    else:
        print(f"the grade for student {i+1} is F")
        grades.append("F")
print(grades)

the grade for student 1 is F
the grade for student 2 is F
['F', 'F']


### Display the result for each student in a tabular format with columns for student name, total marks, percentage, and grade.

In [141]:
final_result = []
for i in range(n):
    final_result.append([marks[i], total_1[i], percentage_1[i], grades[i]])
print(final_result)

[[array([12., 13.]), 25.0, 12.5, 'F'], [array([24., 35.]), 59.0, 29.5, 'F']]


In [148]:
import pandas as pd 
df = pd.DataFrame(final_result ,columns =['marks', 'total', 'percentage', 'grades'] , index=['student 1', 'student 2'] )
print(df)

                  marks  total  percentage grades
student 1  [12.0, 13.0]   25.0        12.5      F
student 2  [24.0, 35.0]   59.0        29.5      F


In [151]:
pd.read_csv(r"C:\Users\PC\Downloads\student note.csv")

Unnamed: 0      marks  total  percentage grades
0  student 1  [12. 13.]   25.0        12.5      F
1  student 2  [24. 35.]   59.0        29.5      F